# Generated by Django 3.2.6 on 2021-08-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=200, unique=True)),
                ('text', models.CharField(max_length=200)),
                ('img', models.CharField(blank=True, max_length=200)),
                ('mark', models.IntegerField()),
                ('total_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('access_times', models.IntegerField()),
                ('create_money', models.IntegerField(default=5000)),
                ('creattime', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('pwd', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('createtime', models.DateField(auto_now=True)),
                ('updatetime', models.DateField(auto_now_add=True)),
                ('is_merchant', models.IntegerField()),
            ],
        ),
    ]
