# Generated by Django 3.2.6 on 2021-08-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('pwd', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('createtime', models.DateField(auto_now=True)),
                ('updatetime', models.DateField(auto_now_add=True)),
                ('is_merchant', models.BooleanField(default=False)),
            ],
        ),
    ]
