# Generated by Django 3.2.6 on 2021-08-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_merchant',
            field=models.IntegerField(default=0),
        ),
    ]
