# Generated by Django 3.2.6 on 2021-08-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210821_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=200, unique=True)),
                ('text', models.CharField(max_length=200)),
                ('img', models.CharField(blank=True, max_length=200)),
                ('mark', models.IntegerField()),
                ('total_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('access_times', models.IntegerField()),
                ('creattime', models.DateField(auto_now=True)),
            ],
        ),
    ]
