# Generated by Django 3.2.6 on 2021-08-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_is_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='addr_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
