# Generated by Django 3.2.6 on 2021-08-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_address_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='create_money',
            field=models.IntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_merchant',
            field=models.IntegerField(),
        ),
    ]
