# Generated by Django 3.2.6 on 2021-08-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_goods_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('goods_id', models.IntegerField()),
                ('text', models.TextField()),
                ('mark', models.DecimalField(blank=True, decimal_places=2, default=5.0, max_digits=10)),
                ('createtime', models.DateField(auto_now=True)),
            ],
        ),
    ]
