# Generated by Django 3.2.6 on 2021-08-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_category_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='createtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
