# Generated by Django 3.2.6 on 2021-08-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('shop_id', models.IntegerField()),
                ('goods_id', models.IntegerField()),
                ('goods_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('goods_num', models.IntegerField()),
                ('goods_img', models.CharField(max_length=200)),
                ('is_chosen', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Favorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('goods_id', models.IntegerField()),
                ('goods_img', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('shop_id', models.IntegerField()),
                ('goods_id', models.IntegerField()),
                ('goods_num', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('trade_time', models.DateField(auto_now_add=True)),
                ('addr', models.CharField(max_length=200)),
                ('pay_state', models.IntegerField()),
                ('delivery_state', models.CharField(max_length=200)),
            ],
        ),
    ]
