# Generated by Django 3.2.6 on 2021-08-21 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorate',
            new_name='Favorite',
        ),
    ]
