# Generated by Django 3.2.6 on 2021-08-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_favorate_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='goods_img',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cart',
            name='goods_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='is_chosen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='goods_img',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='addr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_state',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_state',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shop_id',
            field=models.IntegerField(blank=True),
        ),
    ]
