# Generated by Django 3.2.6 on 2021-08-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='goods_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
